language: elixir
elixir:
  - 1.9
env:
  global:
    - MIX_ENV=test
    - ENCRYPTION_KEYS="nMdayQpR0aoasLaq1g94FLba+A+wB44JLko47sVQXMg=,L+ZVX8iheoqgqb22mUpATmMDsvVGtafoAeb0KN5uWf0="
    - SECRET_KEY_BASE="GLH2S6EU0eZt+GSEmb5wEtonWO847hsQ9fck0APr4VgXEdp9EKfni2WO61z0DMOF"
script:
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash) # send coverage report
cache:
  directories:
    - _build
    - deps