language: elixir
matrix:
  include:
    - elixir: 1.10.4
      otp_release: 22.3.4.12
    - elixir: 1.11.0
      otp_release: 23.0.4
env:
  global:
    - MIX_ENV=test
    - ENCRYPTION_KEYS="nMdayQpR0aoasLaq1g94FLba+A+wB44JLko47sVQXMg=,L+ZVX8iheoqgqb22mUpATmMDsvVGtafoAeb0KN5uWf0="
    - SECRET_KEY_BASE="GLH2S6EU0eZt+GSEmb5wEtonWO847hsQ9fck0APr4VgXEdp9EKfni2WO61z0DMOF"
script:
  - mix deps.get
  - mix compile --warnings-as-errors
  - mix coveralls.json
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - bash <(curl -s https://codecov.io/bash) # send coverage report
cache:
  directories:
    - _build
    - deps
