language: elixir
elixir:
  - 1.8
env:
  global:
    - MIX_ENV=test
    - ENCRYPTION_KEYS="nMdayQpR0aoasLaq1g94FLba+A+wB44JLko47sVQXMg=,L+ZVX8iheoqgqb22mUpATmMDsvVGtafoAeb0KN5uWf0="
    - SECRET_KEY_BASE="2PzB7PPnpuLsbWmWtXpGyI+kfSQSQ1zUW2Atz/+8PdZuSEJzHgzGnJWV35nTKRwx"
script:
  - mix test
cache:
  directories:
    - _build
    - deps